version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      - echo Building the Go code...
      - go build backend-kendo-tutorial
artifacts:
  files:
    - backend-kendo-tutorial